import type { Metadata } from "next";
import SidebarContent from "@/components/phsicsResource/SidebarContent";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className="mt-32 px-10">
        <section className="w-full gap-6 grid grid-cols-4">
          <aside id="side-bar" >
            <SidebarContent />
          </aside>
          <section className="col-span-3">
            <div className="mx-auto border rounded-lg mb-12  p-4">
              {children}
            </div>
          </section>
        </section>
      </main>
    </>
  );
}
